apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Docker2
  template:
    metadata:
      labels:
        app: Docker2
    spec:
      containers:
      - name: docker2
        image:  demo9.azurecr.io/demo9:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockercontainer2

---
apiVersion: v1
kind: Service
metadata:
  name: docker2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Docker2